### ISSUE TITLE
`--dlg` gives error when trying to non-interactively download files

### ISSUE THREAD

**Issue by bendwyer** [Texiwill/aac-lib#10]
I am trying to automate the download of ESXi images. Currently I'm running into an issue where `--dlgl` will find the image, but `--dlg` will give the following error:

```
No Downloads Available
/usr/local/bin/vsm.sh: line 2928: [: All: unary operator expected
Existing All in /home/vagrant/downloads/dlg_All/
Local:/home/vagrant/downloads/dlg_//
```

Here is the `--dlgl` command I am using:
```
vagrant@ubuntu2010:~$ /usr/local/bin/vsm.sh --repo /home/vagrant/downloads -y -u user --dlgl VMware-VMvisor-Installer-7.0U2a
Using the following options:
	Version:	6.5.7
	Username:		user
	Save Credentials:	0
	OS Mode:        ubuntu
	VSM XML Dir:	/tmp/vsm.vagrant
	Repo Dir:	/home/vagrant/downloads
	Dryrun:		0
	Force Download:	0
	Checksum:	0
	Historical Mode:0
	Symlink Mode:	0
	Reset XML Dir:	0
	Use credstore:	1
VMware-VMvisor-Installer-7.0U2a-17867351.x86_64.iso
```

And here is the `--dlg` command I am using. I'm taking the output from `--dlgl` and plugging it into `--dlg`.
```
vagrant@ubuntu2010:~$ /usr/local/bin/vsm.sh --repo /home/vagrant/downloads -y -u user --dlg VMware-VMvisor-Installer-7.0U2a-17867351.x86_64.iso
Using the following options:
	Version:	6.5.7
	Username:		user
	Save Credentials:	0
	OS Mode:        ubuntu
	VSM XML Dir:	/tmp/vsm.vagrant
	Repo Dir:	/home/vagrant/downloads
	Dryrun:		0
	Force Download:	0
	Checksum:	0
	Historical Mode:0
	Symlink Mode:	0
	Reset XML Dir:	0
	Use credstore:	1
	Saving to /home/vagrant/.vsmrc
	Oauth:		1
No Downloads Available
/usr/local/bin/vsm.sh: line 2928: [: All: unary operator expected
Existing All in /home/vagrant/downloads/dlg_All/
Local:/home/vagrant/downloads/dlg_//
```

Host info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

EDIT - Interactively navigating to the file using the numbered prompts works without issue, and I am able to find and successfully download the `VMware-VMvisor-Installer-7.0U2a-17867351.x86_64.iso` file.

**Comment by Texiwill** [comment]
Yes, there is something wrong in the code. Working it now.

**Comment by Texiwill** [comment]
This is fixed in v6.5.8. Please download and test.

**Comment by BadikovVV** [comment]
Testing as in example vsm.sh -y --dlg CLI\.\*\.x86_64.tar.gz
	
	Using the following options:
	Version:	6.7.7
	OS Mode:        ubuntu
	VSM XML Dir:	/tmp/vsm.user
	Repo Dir:	/tmp/vsm.user
	Dryrun:		0
	Rebuild:	0
	Force Download:	0
	Checksum:	1
	Historical Mode:0
	Symlink Mode:	0
	Reset XML Dir:	0
	Nested: 0
	Verify Mode:	0
	Retry Count:	8
	Use credstore:	1
	Saving to /home/user/.vsmrc
	Authenticating... May take up to 90s... 12-20s is normal...
	Oauth:		1
	/tmp/vsm.user/depot.vmware.com/PROD/cha 100%[========================================================================================================>]   2.69K  --.-KB/s    in 0s
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
jq: error (at /tmp/vsm.user/depot.vmware.com/PROD/channel/_.xhtml:0): Cannot iterate over null (null)

**Comment by Texiwill** [comment]
Thank you for trying with the latest version. The CLI package is no longer available from VMware and the newlocs.json file shows this. I will put in some better error reporting. Use `Perl-SDK-7\.\*\.x86_64.tar.gz` instead as your search term.

You can also use the --rebuild --dry run options to create your own newlocs.json file which contains the data to use. There is a patch coming to fix getting the latest version when the regex is specified. The README has an updated with a different example.

Granted I have not tested on Ubuntu yet but it should work.

**Comment by Texiwill** [comment]
The latest relast now has better error checking and will work as expected.
