### ISSUE TITLE
Feature-Request: add support for Alpine-linux as host OS

### ISSUE THREAD

**Issue by MaxPeal** [Texiwill/aac-lib#13]
please add Alpine-linux as host OS,
as it is significant smaller at the disk and ram usage.

**Comment by Texiwill** [comment]
However, the requirements of LinuxVSM is such that you will be bringing in many components that will grow that disk significantly.

**Comment by Texiwill** [comment]
I can install everything in Alpine, but the latest version of the nodejs functions I use are not supported by the latest version of Alpine. I am working on some other way to make things work but so far it does not look good.

**Comment by Texiwill** [comment]
Ah ha! Got it. Alpine support will be in the next release v6.7.1.
