### ISSUE TITLE
Connection reset by peer with vsm_favorites.sh

### ISSUE THREAD

**Issue by fpollet** [Texiwill/aac-lib#17]
Hello

For some time, I have regularly disconnections with the command "/usr/local/bin/vsm_favorites.sh --n+1":

2022-04-04 13:22:32 (6.01 MB/s) - Read error at byte 2184469734/2399780864 (Connection reset by peer). 
wget  --progress=bar:force --load-cookies /data/tmp/ocookies.txt --header=User-Agent:
Authenticating... May take up to 90s... 12-20s is normal...

**Comment by Texiwill** [comment]
Please run vsm.sh directly and look at the output. Some questions:
 - From where are you running the command (Country)?
 - Are you using this through a VPN?
 - Do you have MFA enabled?
 - What is your version of vsm.sh?
 - Is there any issues reaching myvmware.com?

**Comment by fpollet** [comment]
• From where are you running the command (Country)? FR
    • Are you using this through a VPN? No
    • Do you have MFA enabled? No
    • What is your version of vsm.sh? 6.7.2
    • Is there any issues reaching myvmware.com? No

I had the same problems re-running "vsm.sh" directly but it seems to be coming from my antivirus. I come back to you to confirm or deny. Thank you
