### ISSUE TITLE
ERROR! couldn't resolve module/action 'timezone'

### ISSUE THREAD

**Issue by fpollet** [Texiwill/aac-lib#20]
Hello,

I gradually updated my server CentOS 7.9 -> AlmaLinux 8.6 -> AlmaLinux 8.7

When updating AlmaLinux 8.6 -> AlmaLinux 8.7, I had the following problem:

Error: Problem: conflicting requests - nothing provides (ansible-core >= 2.12.2 with ansible-core < 2.13) needed by ansible-5.4.0-3.el8.noarch

I used the following solution: yum update –allowerasing

The ansible-5.4.0-3.el8.noarch package has been removed in favor of the ansible-core-2.13.3-1.el8.x86_64 package which contains the ansible executable.

Since when I use the provided install.sh script which calls the aac-lib/base installers to install vsm I get the following error message:

ERROR! couldn't resolve module/action 'timezone'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/aac-base/ansible/aac-base-tz.yaml': line 263, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

     - name: Set timezone
       ^ here

Thank you in advance for your help.

**Comment by Texiwill** [comment]
Hello, At this time AlmaLinux is not on the supported list. It looks like there is a major issue with the Ansible version you are using. Almost like it went backwards to an older version of ansible.

**Comment by Texiwill** [comment]
Hello,

I switched timezone to community.general.timezone already so the with_items has dropped out completely. But good catch. Can you get me the contenst of /etc/os-release on AlmaLinux? I am updating everything for Rocky9 at the moment. So I can add AlmaLinux 9 as well.

**Comment by fpollet** [comment]
```
cat /etc/redhat-release 
AlmaLinux release 8.8 (Sapphire Caracal)
```

**Comment by Texiwill** [comment]
Support for AlmaLinux 9 was added as well as updates for newest version of ansible used. Also fixed the dependency checks.
