### ISSUE TITLE
vsm.sh get TimeoutError in Authenticating proccess

### ISSUE THREAD

**Issue by ihumster** [Texiwill/aac-lib#21]
After run vsm.sh Authenticating proccess down by timeout (30 sec).

```
vsm.sh
Using the following options:
        Version:        6.8.2
        OS Mode:        ubuntu
        VSM XML Dir:    /tmp/vsm.ihumster
        Repo Dir:       /opt/dist-repo
        Dryrun:         0
        Rebuild:        0
        Force Download: 0
        Checksum:       0
        Historical Mode:1
        Symlink Mode:   0
        Reset XML Dir:  0
        Nested: 0
        Verify Mode:    0
        Retry Count:    8
        Use credstore:  1

Continue with VSM (Y/n)?

        Saving to /home/ihumster/.vsmrc
        Authenticating... May take up to 90s... 12-20s is normal...
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /tmp/vsm.ihumster/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:113:111
```

**Comment by ihumster** [comment]
It turns out to start with 5-10 attempts

**Comment by ihumster** [comment]
@Texiwill hello. You can do something with this issue? Maybe there is a way to increase the timeout?

**Comment by Texiwill** [comment]
Hello,

This happens when the web page retrieved does not match the pattern to which to search. It implies usually that the page retrieved is changed in some way but I do not see this as an issue. I can increase or make the time out settable but the issue is general something to do with reachability to www.vmware.com. Have you been able to get to www.vmware.com and login there successfully? Please let me know if this is an issue.

Thank you,
Texiwill

**Comment by Texiwill** [comment]
Timeout added, do the following:
get latest
vsm.sh --cleanall
vsm.sh --timeout 120 # for 120 seconds

**Comment by ihumster** [comment]
I get latest
make 
vsm.sh --clean
vsm.sh --timeout 120

but get same error
```
ihumster@vsm:~$ vsm.sh --timeout 120
Using the following options:
        Version:          6.8.4
        OS Mode:          ubuntu
        VSM XML Dir:      /tmp/vsm.ihumster
        Repo Dir:         /opt/dist-repo
        Dryrun:           0
        Rebuild:          0
        Force Download:   0
        Checksum:         0
        Historical Mode:  1
        Symlink Mode:     0
        Reset XML Dir:    0
        Nested:           0
        Verify Mode:      0
        Retry Count:      8
        Use credstore:  1

Continue with VSM (Y/n)?

        Saving to /home/ihumster/.vsmrc
        Authenticating... May take up to 90s... 12-20s is normal...
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /tmp/vsm.ihumster/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:113:111
        DNS or WSL1 issue? Unable to reach My VMware
```

**Comment by Texiwill** [comment]
Hello,

The software is unable to reach www.vmware.com. Please ensure that site is reachable by your Ubuntu system. I suggest using elinks or lynx to determine if you can reach www.vmware.com. A ping would also help. You either have a routing, proxy, firewall, or DNS issue. This happens on the initial request to reach www.vmware.com and it fails. There is a 30s timeout here just to raise www.vmware.com. I will ensure the timeout affects this request as well but check your network.

**Comment by ihumster** [comment]
Indeed, with my Ubuntu www.vmware.com gets 403 Forbidden.
