### ISSUE TITLE
VSM Linux Install: fatal: [localhost]: FAILED! => {"msg": "template error while templating string: No filter named 'basename'

### ISSUE THREAD

**Issue by DennisFaucher** [Texiwill/aac-lib#22]
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

./vsm-install.sh

fatal: [localhost]: FAILED! => {"msg": "template error while templating string: No filter named 'basename'.. String: {{ ansible_python.executable|basename }}-pip"}

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=1    skipped=6    rescued=0    ignored=1

Failed to install LinuxVSM.
VSM is now in /usr/local/bin/vsm.sh

**Comment by Texiwill** [comment]
This was fixed in the latest version of the ansible playbooks which had an issue with a conditional. This works on Ubuntu 20 and 24 now.
