### ISSUE TITLE
Oauth: Error

### ISSUE THREAD

**Issue by accad** [Texiwill/aac-lib#24]
Running on CentOS 7

Getting issues, so created a new account on the Linux box and started from scratch, no configurations

$ git clone https://github.com/Texiwill/aac-lib.git
Cloning into 'aac-lib'...
remote: Enumerating objects: 3730, done.
remote: Counting objects: 100% (925/925), done.
remote: Compressing objects: 100% (271/271), done.
remote: Total 3730 (delta 672), reused 781 (delta 654), pack-reused 2805
Receiving objects: 100% (3730/3730), 211.18 MiB | 60.86 MiB/s, done.
Resolving deltas: 100% (2417/2417), done.

$ cd aac-lib/vsm/

$ ./vsm.sh  -u $USERNAME -p $PASSWORD
Using the following options:
        Version:          6.9.0
        Username:         <REDACTED>
        Save Credentials: 0
        OS Mode:          centos
        VSM XML Dir:      /tmp/vsm.vsm
        Repo Dir:         /tmp/vsm.vsm
        Dryrun:           0
        Rebuild:          0
        Force Download:   0
        Checksum:         0
        Historical Mode:  0
        Symlink Mode:     0
        Reset XML Dir:    0
        Nested:           0
        Verify Mode:      0
        Retry Count:      8
        Use credstore:  0

Continue with VSM (Y/n)?
y
        Saving to /home/vsm/.vsmrc
        Authenticating... May take up to 90s... 12-20s is normal...  
        Cleaning Module Cache
        Installing necessary modules
        Finished installing necessary modules
Error: No element found for selector: #email
    at assert (/tmp/vsm.vsm/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.type (/tmp/vsm.vsm/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:378:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmp/vsm.vsm/node-bm.js:53:2
        Oauth:          Error

I can login to Broadcom with the same credentials.

What am I missing? Anything I can provide to help you?

**Comment by Texiwill** [comment]
The new code for the Broadcom site is not working yet as Broadcom's OKTA integration is not working with Linux machnes at this time.
