### ISSUE TITLE
aac-lib installation on a vanilla (non root) VMware Photon OS virtual machine

### ISSUE THREAD

**Issue by dcasota** [Texiwill/aac-lib#6]
Hi,
The manual install of aac-lib' LinuxVSM on a vanilla VMware Photon OS 3 vm returns an error ```ERROR! the playbook: ansible/LinuxVSM.yaml could not be found``` appears (see file attached). 
[screendump.txt](https://github.com/Texiwill/aac-lib/files/5342288/screendump.txt)
I've created a local user account and used sudo but the menu like in the docs right after checking ansible doesn't appear.
-Daniel

**Comment by Texiwill** [comment]
Please use the 'install.sh' file as that has the correct approach to do the install.

**Comment by dcasota** [comment]
@Texiwill Many thanks for your quick reply.

Wohoo! install.sh did it. Wasn't aware of the installer script entry in the docs for vsm though. It works successfully on the same virtual machine and in a vanilla retest.

```
sudo tdnf install -y wget
wget https://raw.githubusercontent.com/Texiwill/aac-lib/master/vsm/install.sh
chmod 755 install.sh
./install.sh
```
Finally, it took almost 20 minutes install time for LinuxVSM on Photon.
```
/usr/local/bin/vsm.sh
```
Okay, yes, the cli-based traversing approach of https://my.vmware.com/group/vmware/downloads/#all_products with favorites based download really helps structuring the repo. Spotted the playbooks update option in the docs, too. Nifty.
