### ISSUE TITLE
Ansible run fails on CentOS 7

### ISSUE THREAD

**Issue by alexdga** [Texiwill/aac-lib#9]
Hi and first ty for this great tool.

When using vsm/install.sh on CentOS 7, ansible run fails executing pip2 install pexpect : 

Error : no module named typing

On CentOS 8, the installer runs without any problem.

**Comment by Texiwill** [comment]
Hello,

Please provide the output of 'rpm -qa centos-release' so that I know exactly which version of CentOS 7 is in use. If that does not work run 'hostnamectl' or 'cat /etc/os-release'.

**Comment by alexdga** [comment]
CentOS 7.9.2009

**Comment by Texiwill** [comment]
Is this running in WSL2?

**Comment by alexdga** [comment]
No it is a pure CentOS 7.9.2009 VM running on vSphere 6.7U3

**Comment by Texiwill** [comment]
downloading and testing against a fresh 'minimal install' of CentOS 7.9.2009 now.

**Comment by Texiwill** [comment]
This looks to be a Python 2.7.5 issue with missing dependencies introduced at CentOS 7.9.  I am investigating hot to work around the issue.

**Comment by alexdga** [comment]
Great news ! Thank you.

**Comment by Texiwill** [comment]
This is now fixed. The problem was the wrong version of PIP was being installed. Ansible stanza fixed to not go past a certain version.

**Comment by alexdga** [comment]
It is now working like a charm. Thank you.
